### ISSUE TITLE
Typo (nazoSAUNA → nazonoSAUNA？)

### ISSUE THREAD

**Issue by pklion** [Per-Terra/butler-pkgs#13]
https://github.com/Per-Terra/butler-pkgs/tree/main/manifests/nazoSAUNA は nazonoSAUNA の誤字でしょうか

入りきらない等の理由でしたらすみません
Identiferなので問題にはならないと思いますが…

**Comment by pklion** [comment]
今更 Scrapbox から取られてることに気づきました…
一応 (GitHub)[https://github.com/nazonoSAUNA] は nazo**no** でユーザ取られてるようですが、ぺるてらさんの御判断にお任せします
すみません

**Comment by Per-Terra** [comment]
この方、いろんな表記があって悩んだんですが、まさに仰るとおりの理由でそのようにしています。GitHubの方もUsernameこそnazonoSAUNAですが、NameはnazoSAUNAに設定なさっているようですしね。
ご協力に感謝します。
